### ISSUE TITLE
Scripts for preparing the data

### ISSUE THREAD

**Issue by achernodub** [dykang/flownet#1]
Hi there!

I have a problem with replicating your experiments on the data preprocessing stage. As it follows from the README: "preprocess them using the scripts under prepare_{arxiv,book}.py".

I don't see such a script in the /code directory, where to find it?

Alternatively, if it is possible to download a pretrained FlowNet model(-s), it could be really helpful!

Thanks a lot for your perfect work!

**Comment by dykang** [comment]
Hi, they are under `code/prep/` directory! Regarding the pre-trained model, the codes I used are pretty much out-dated and not compatible with the latest TensorFlow. I am working on transferring to pytorch now but it is pretty slow. Though I'm happy to help you start to replicate!
